import { bebasNeue, montserrat, lato } from "./fonts";
import "../styles/globals.scss";
import Header from "@/components/layout/header/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} ${montserrat.variable} ${lato.variable}`}>
       <Header />
        {children}
      </body>
    </html>
  );
}
